version: 2.1

workflows:
  build:
    jobs:
      - build:
          context:
            - ssdK8S

jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:18.06.3-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Prepare Environment
          command: |
            apk add curl
            curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
            chmod +x ./kubectl
            mv ./kubectl /usr/local/bin
            date +%Y%m%d_%H%M > /tmp/timestamp
            echo $kubeconfig > /tmp/kubeconfig
      - run:
          name: Authenticate with Docker
          command: |
            docker login --username ${DOCKER_USERNAME} -p "${DOCKER_PASSWORD}"
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/app.tar | true
      - run:
          name: Build application Docker image
          command: |
            TS=`cat /tmp/timestamp`
            echo $TS
            ##
            docker build --cache-from=app  -t jzmatrix/zconnector:$TS -t jzmatrix/zconnector:latest .
            ##
            mkdir -p /caches
            docker save -o /caches/app.tar jzmatrix/zconnector:latest
            ##
            docker push jzmatrix/zconnector:$TS
            docker push jzmatrix/zconnector:latest
            ##
            kubectl set image deployment/zconnector zconnector=jzmatrix/zconnector:$TS --kubeconfig /tmp/kubeconfig
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/app.tar