version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:18.06.3-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Authenticate with Docker
          command: |
            docker login --username ${DOCKER_USERNAME} -p "${DOCKER_PASSWORD}"
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/app.tar | true
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=app -t jzmatrix/${GCR_PROJECCIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1} .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/app.tar app
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/app.tar
      - run:
          name: Push app image
          command: |
            docker push jzmatrix/${GCR_PROJECCIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1
 
#  docker_push:
#    docker:
#      - image: bayesimpact/circleci
#    working_directory: ~/repo
#    steps:
#      - checkout
#      - setup_remote_docker
#      - run:
#          name: Authenticate with Docker
#          command: |
#            echo "${DOCKER_PASSWORD}" | docker login --username ${DOCKER_USERNAME} --password-stdin
#      - run:
#          name: Build app image
#          command: |
#            docker build --rm=false \
#            -t gcr.io/${GCR_PROJECT}/myapp:${CIRCLE_SHA1} \
#            -t gcr.io/${GCR_PROJECT}/myapp:${CIRCLE_BRANCH} \
#            -f ./Dockerfile .
#      - run:
#          name: Push app image
#          command: |
#            docker push gcr.io/${GCR_PROJECT}/myapp:${CIRCLE_SHA1}
#            docker push gcr.io/${GCR_PROJECT}/myapp:${CIRCLE_BRANCH}